name: studyflash
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  firebase_auth: ^5.5.2
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: true 
  web: 
  generate: true 
  image_path: "assets/images/logf.png"

flutter_native_splash:
  color: "#0B5DAE" # Color de fondo
  image: assets/images/logf.png # Ruta del logo de carga
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - assets/env/.env
